### ISSUE TITLE
[Meta] Collaborate to keep up with on-going DR2 development

### ISSUE THREAD

**Issue by maxbechtold** [ErlerPhilipp/dr2_logger#1]
Hi there, I just discovered your project - fantastic to see further tools being developed for DiRT Rally 2.0.

Since this and my [time-recorder](https://github.com/soong-construction/dirt-rally-time-recorder/issues/8) share a common data basis to identify tracks and cars, are you interested in sharing these parts? 

Perhaps mutual pull requests make sense if one includes new tracks and cars first. I only own season 1 & 2 so far, thus don't yet support Greece and Finland, for example. 

Further common interests I'm thinking of:
- discover a smart way to distinguish cars with identical RPM values
- make a section on how to run multiple UDP consumers simultaneously
- properly handle RPM irregularities after service (I found them to be higher than usual)
- cope with UDP changes in DR2 releases after 1.9

Also, I'll gladly link to your tool in the README, and would enjoy seeing another in yours :).

**Comment by ErlerPhilipp** [comment]
Hi Max,

sorry for the late answer. I didn't get a notificaton for some reason.

Yes, I'm happy to cooperate. Feel free to pull data from my repo and please notify me when you have something new. I too only own season 1 and 2 atm. Still waiting for a sale...

- discover a smart way to distinguish cars with identical RPM values: 
  - We can distinguish some cars because some confusions are between rally and rally cross cars. This would be clear from the track type then.
  - Maybe, we can do something with the car size, e.g. spawn position.
- make a section on how to run multiple UDP consumers simultaneously
  - This is included in my readme. Simply add a second entry in the hardware_settings_config.xml.
  - I had some code mirroring the UDP data but that isn't necessary.
- properly handle RPM irregularities after service (I found them to be higher than usual)
  - I didn't notice so far. Sounds strange...
- cope with UDP changes in DR2 releases after 1.9
  - I think my tool works unchanged. Do you have a reference for changes?

I'll link your tool in my readme soon. (next release or so)

Also, feel free to contact me personally for direct exchange of ideas.

**Comment by maxbechtold** [comment]
No problem.

Awesome! Concerning the issues
- there are still some cars, especially in the R5 class, with identical values
- car size/position is indeed something I should look into, great idea
- actually, I only learnt from your code that there are both *current* and *idle* rpm values in the UDP data - I only knew about the former which is of course instable. So, using your rpm values I managed to get out *dirt-rally-time-recorder* V2.0.0 with DR2 support - Kudos!
- no, and I don't actually expect changes to the UDP output. My reference is linked as a [resource](https://docs.google.com/spreadsheets/d/1UTgeE7vbnGIzDz-URRk2eBIPc_LR1vWcZklp7xD9N0Y/edit#gid=0)

Another hint: since you included Wales and some other "old" tracks - Sweet Lamb has a different track length, but perhaps you already noticed (looks about right in https://github.com/ErlerPhilipp/dr2_logger/blob/master/dr2specific.py)
